// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzygrnctogbsxbzlvsow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6eWdybmN0b2dic3hiemx2c293Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2OTczMDcsImV4cCI6MjA3MjI3MzMwN30.4an2-au8XmBaUo3N50PlQyS6qr0WNrI2yqaUHAuOprM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});